import os as _os, sys as _sys
_HERE = _os.path.dirname(_os.path.abspath(__file__))
_sys.path.insert(0, _HERE)
_ROOT = _os.path.dirname(_HERE)
_os.makedirs(_os.path.join(_ROOT, 'figures'), exist_ok=True)
_os.chdir(_os.path.join(_ROOT, 'data'))

"""Placebo covariates: how much spatial clustering would adjustment for ANY covariates with the same
spatial structure as the need covariates remove?
With 42 areas, regression on a few spatially smooth covariates absorbs part of any broad regional
pattern, whatever its cause. Placebo covariates are generated by Moran spectral randomisation (the
'pair' method of Wagner and Dray 2015): the centred covariate matrix is expressed in the basis of Moran
eigenvectors (eigenvectors of the doubly centred, symmetrised contiguity matrix, sorted by eigenvalue),
and the coefficients of consecutive pairs of eigenvectors are rotated by random angles, jointly for all
covariates. Each placebo set therefore has exactly the covariance matrix of the real covariates and
approximately their Moran's I, but its high and low values lie in different places.
For the real covariates and for each placebo set, the item-level analysis is repeated with the same
Freedman-Lane permutation test (9,999 permutations, without the refinement to 99,999 used in the
main analysis, identically for real and placebo covariates) and the overall neighbour contrast is recomputed on the
need-adjusted profiles excluding dispensing appliances (as in need_similarity.py).
Variants: need (placebos for all five primary covariates, compared with the primary model);
age_deprivation (placebos for the three age and deprivation covariates); morbidity_increment (real age
and deprivation covariates plus placebos for the two QOF components residualised on them, compared
with the primary model).
Usage: python3 placebo_covariates.py [n_need n_agedep n_increment]   (defaults 200 100 100)"""
import numpy as np, pandas as pd, pickle, json, sys, time
from need_adjustment_core import primary_covariates, resid_maker, load_covariates, moran_rows, bh
TOL = 1e-12; POS = 1e-12
NREP = [int(x) for x in sys.argv[1:4]] if len(sys.argv) >= 4 else [200, 100, 100]
A = np.load('A_af.npy'); W = np.load('W_contig.npy'); Wb = np.load('Wb_contig.npy')
codes = pickle.load(open('codes_af.pkl', 'rb')); n = len(codes); iu = np.triu_indices(n, 1); nb = Wb[iu] == 1
app = pd.read_csv('moran_af.csv').appliance.astype(bool).values
C = load_covariates(codes)
Y = A.T.astype(float); Yna = A[:, ~app].T.astype(float); mna = Yna.mean(1)
Xprim = primary_covariates(codes); Xad = np.column_stack([C.age_65plus, C.age_u18, C.imd2025]).astype(float)
X1 = np.column_stack([np.ones(n), Xad]); PCres = Xprim[:, 3:] - X1 @ np.linalg.lstsq(X1, Xprim[:, 3:], rcond=None)[0]
# Moran eigenvectors: eigenvectors of H Ws H orthogonal to the constant vector
Ws = (W + W.T) / 2; H = np.eye(n) - np.ones((n, n)) / n
lam, V = np.linalg.eigh(H @ Ws @ H)
keep = np.abs(V.sum(0)) < 1e-8 * n; lam, V = lam[keep], V[:, keep]
o = np.argsort(lam)[::-1]; lam, V = lam[o], V[:, o]
assert V.shape[1] == n - 1


def moran_cols(X):
    Z = X - X.mean(0); return (Z * (W @ Z)).sum(0) / (Z ** 2).sum(0)


def placebo(X, rng):
    """Moran spectral randomisation, pair method: rotate the Moran-eigenvector coefficients of consecutive
    pairs of eigenvectors by random angles (the last, unpaired eigenvector gets a random sign), jointly
    for all covariate columns."""
    mu = X.mean(0); B = V.T @ (X - mu); R = np.zeros((n - 1, n - 1))
    for i in range(0, n - 2, 2):
        a = rng.uniform(0, 2 * np.pi); R[i:i + 2, i:i + 2] = [[np.cos(a), -np.sin(a)], [np.sin(a), np.cos(a)]]
    if (n - 1) % 2:
        R[-1, -1] = rng.choice([-1.0, 1.0])
    return V @ (R @ B) + mu


def jsd_pairs(P, eps=1e-10):
    P = P + eps; P = P / P.sum(1, keepdims=True)
    p, r = P[iu[0]], P[iu[1]]; m = 0.5 * (p + r)
    return np.sqrt(np.maximum(0.5 * (p * np.log(p / m)).sum(1) + 0.5 * (r * np.log(r / m)).sum(1), 0))


def run(Xc, seed, N=9999):
    Mres, k = resid_maker(Xc); E = Y @ Mres
    sst = ((Y - Y.mean(1, keepdims=True)) ** 2).sum(1); r2 = 1 - (E ** 2).sum(1) / sst
    I = moran_rows(E, W); g = np.random.default_rng(seed); cnt = np.zeros(len(E))
    for _ in range(N):
        R = E[:, g.permutation(n)] @ Mres
        cnt += moran_rows(R, W) >= I - TOL
    p = (cnt + 1) / (N + 1); q = bh(p)
    dv = jsd_pairs(np.clip(mna[:, None] + Yna @ Mres, 0, None).T)
    return dict(nominal=int(((p < 0.05) & (I > POS)).sum()), clustered=int(((q < 0.05) & (I > POS)).sum()),
                median_R2=float(np.median(r2)), neighbour_pct=float(100 * (dv[~nb].mean() - dv[nb].mean()) / dv[~nb].mean()))


t0 = time.time(); rng = np.random.default_rng(2026)
real = {'unadjusted': run(np.zeros((n, 0)), 900), 'age_deprivation': run(Xad, 901), 'primary': run(Xprim, 902)}
print('real', json.dumps(real), f'{time.time() - t0:.0f}s', flush=True)
variants = {'need': (lambda: placebo(Xprim, rng), NREP[0], 'primary'),
            'age_deprivation': (lambda: placebo(Xad, rng), NREP[1], 'age_deprivation'),
            'morbidity_increment': (lambda: np.column_stack([Xad, placebo(PCres, rng)]), NREP[2], 'primary')}
rows = []; summary = {}
for v, (make, nrep, ref) in variants.items():
    for r in range(nrep):
        Xp = make()
        Xr = {'need': Xprim, 'age_deprivation': Xad, 'morbidity_increment': np.column_stack([Xad, PCres])}[v]
        if v != 'morbidity_increment':     # placebo covariates keep the covariance of the real covariates
            assert np.allclose(np.cov(Xp.T), np.cov(Xr.T))
        d = run(Xp, 1000 + len(rows)); d.update(variant=v, rep=r)
        d.update({f'moran_x{j + 1}': float(x) for j, x in enumerate(moran_cols(Xp))})
        Q1, _ = np.linalg.qr(np.column_stack([np.ones(n), Xr])); Q2, _ = np.linalg.qr(np.column_stack([np.ones(n), Xp]))
        d['mean_canonical_corr_with_real'] = float(np.linalg.svd(Q1[:, 1:].T @ Q2[:, 1:], compute_uv=False).mean())
        rows.append(d)
        if r % 20 == 19:
            print(v, r + 1, f'{time.time() - t0:.0f}s', flush=True)
    D = pd.DataFrame([x for x in rows if x['variant'] == v])
    summary[v] = {c: dict(mean=float(D[c].mean()), p05=float(D[c].quantile(.05)), p95=float(D[c].quantile(.95)),
                          min=float(D[c].min()), max=float(D[c].max())) for c in ['nominal', 'clustered', 'median_R2', 'neighbour_pct']}
    summary[v]['n_sets'] = nrep; summary[v]['compared_with'] = ref
    summary[v]['mean_moran_I_of_placebo_covariates'] = [float(D[c].mean()) for c in D.columns if c.startswith('moran_x')]
    summary[v]['mean_canonical_corr_with_real'] = float(D.mean_canonical_corr_with_real.mean())
    summary[v]['share_of_placebos_reducing_as_much_as_real'] = {c: float((D[c] <= real[ref][c]).mean()) for c in ['nominal', 'clustered', 'neighbour_pct']}
pd.DataFrame(rows).to_csv('placebo_runs.csv', index=False)
out = dict(real=real, placebo=summary, permutations=9999,
           moran_I_real_primary=moran_cols(Xprim).round(3).tolist(), moran_I_real_age_deprivation=moran_cols(Xad).round(3).tolist(),
           moran_I_morbidity_components_residualised=moran_cols(PCres).round(3).tolist())
json.dump(out, open('placebo_summary.json', 'w'), indent=1)
print(json.dumps(out, indent=1))
